"""Add client to events

Revision ID: 36942623b801
Revises: aecc0d98b509
Create Date: 2026-09-09 16:20:16.010085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36942623b801'
down_revision = 'aecc0d98b509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key('fk_events_client_id_clients', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_client_id_clients', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_client_id'))
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
