"""Add client to gallery

Revision ID: 8cd81dd4453e
Revises: 36942623b801
Create Date: 2026-09-09 16:37:04.103119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd81dd4453e'
down_revision = '36942623b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_gallery_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key('fk_gallery_client_id_clients', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gallery_client_id_clients', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_gallery_client_id'))
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
